export const problemCards = 
// TODO: Fix These
 [

  // These create one exsisting token and one not-exsisting token
  "Evil Comes to Fruition",
  "One Dozen Eyes",
  // A HUGE PROBLEM ALL IT'S OWN, but also makes exsisting and non-exsisting tokens
  "Sarpadian Empires, Vol. VII",

  //OLD and make no exsisting token
  "Abian, Luvion Usurper",
  "Balduvian Dead",
  "Baru, Fist of Krosa",
  "Basalt Golem",
  "Blessed Sanctuary",
  "Bone Rattler",
  "Boris Devilboon",
  "Bottle of Suleiman",
  "Broken Visage",
  "Caribou Range",
  "Carrion",
  "Chicken Egg",
  "Diamond Kaleidoscope",
  "Dune-Brood Nephilim",
  "Dungeon Master",
  "Elephant Resurgence",
  "Errand of Duty",
  "Evil Boros Charm",
  // For now this makes 4/4 beasts, but eventually should make Phyrexian Beast tokens
  "Ezuri's Predation",
  "Firecat Blitz",
  "Generated Horizons",
  "Gemini Engine",
  "Giant Caterpillar",
  "Goblin Scouts",
  "Gorilla Tactics",
  "Gunk Slug",
  "Handy Dandy Clone Machine",
  "Haunted Angel",
  "Hazezon Tamar",
  "Helm of Kaldra",
  "Homarid Spawning Bed",
  "Hunted Horror",
  "Imaginary Friends",
  "Infernal Genesis",
  "Jungle Patrol",
  "Keeper of the Beasts",
  "Kjeldoran Home Guard",
  "Master of the Hunt",
  "Master of the Wild Hunt Avatar",
  "Mirrored Lotus",
  "Mongrel Pack",
  "Monkey Cage",
  "Nuisance Engine",
  "Ovinomancer",
  "Oyobi, Who Split the Heavens",
  "Penumbra Bobcat",
  "Penumbra Kavu",
  "Phantasmal Sphere",
  "Phelddagrif",
  "Pick Your Poison",
  "Pure Reflection",
  "Questing Phelddagrif",
  "Rally the Horde",
  "Riptide Replicator",
  "Saproling Burst",
  "Sek'Kuar, Deathkeeper",
  "Serpent Generator",
  "Skirk Ridge Exhumer",
  "Slivdrazi Monstrosity",
  "Sound the Call",
  "Spawning Pit",
  "Spike Breeder",
  "Spiny Starfish",
  "Spirit Mirror",
  "Splintering Wind",
  "Summoning Station",
  "Symbol Status",
  "Tatsumasa, the Dragon's Fang",
  "Tetravus",
  "The Iron Guardian Stirs",
  "The Legend of Arena",
  "Time Sidewalk",
  "Tomb of Urami",
  "Tombstone Stairwell",
  "Uktabi Kong",
  "Volrath's Laboratory",
  "Wall of Kelp",
  "Wand of the Elements",
  "Waste Land",
  "Waylay",
  "Wirefly Hive",
  "Wurmcalling"
];